//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Plik.cpp
//  @ Date : 19.05.2025
//  @ Author : overstimulation
//
//

#include <chrono>
#include <ctime>
#include <iomanip>
#include <sstream>
#include "Plik.h"

string Plik::getNazwa()
{
    return nazwa;
}

int Plik::getRozmiar()
{
    return rozmiar;
}

string Plik::getDataDodania()
{
    return dataDodania;
}

string Plik::getTresc()
{
    return tresc;
}

Plik::Plik(string nazwa, int rozmiar, string tresc) : nazwa(nazwa), rozmiar(rozmiar), tresc(tresc)
{
    auto teraz = std::chrono::system_clock::now();
    std::time_t aktualny_czas = std::chrono::system_clock::to_time_t(teraz);
    std::tm tm = *std::localtime(&aktualny_czas);
    std::ostringstream oss;
    oss << std::put_time(&tm, "%Y-%m-%d");
    dataDodania = oss.str();
}
