//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kurs.cpp
//  @ Date : 19.05.2025
//  @ Author :
//
//

#include "Kurs.h"
#include "User.h"
#include "Student.h"
#include "Wykladowca.h"
#include "Skrzynka.h"
#include "Ocena.h"
#include "Plik.h"

string Kurs::getNazwa()
{
    return nazwa;
}

list<Student *> Kurs::getStudenci()
{
}

list<Wykladowca *> Kurs::getWykladowcy()
{
}

list<Skrzynka *> Kurs::getSkrzynki()
{
}

void Kurs::dodajSkrzynke(Skrzynka *skrzynka)
{
}

void Kurs::dodajOcene(Ocena *ocena)
{
}

void Kurs::dodajUczestnika(User *uczestnik)
{
}

bool Kurs::usunSkrzynke(int id)
{
}

bool Kurs::usunOcene(Ocena *ocena)
{
}

bool Kurs::usunUczestnika(int id)
{
}

void Kurs::dodajPlikDoSkrzynki(int idSkrzynki, Plik *plik)
{
}

Kurs::Kurs(string nazwa)
{
}
