//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kurs.cpp
//  @ Date : 19.05.2025
//  @ Author :
//
//

#include "Kurs.h"
#include "User.h"
#include "Student.h"
#include "Wykladowca.h"
#include "Skrzynka.h"
#include "Ocena.h"
#include "Plik.h"

string Kurs::getNazwa()
{
	return nazwa;
}

list<Student *> Kurs::getStudenci()
{
	return studenci;
}

list<Wykladowca *> Kurs::getWykladowcy()
{
	return wykladowcy;
}

list<Skrzynka *> Kurs::getSkrzynki()
{
	return skrzynkiPlikow;
}

void Kurs::dodajSkrzynke(Skrzynka *skrzynka)
{
	skrzynkiPlikow.push_back(skrzynka);
}

void Kurs::dodajOcene(Ocena *ocena)
{
	oceny.push_back(ocena);
}

void Kurs::dodajStudenta(Student *student)
{
	for (Student *s : studenci)
	{
		if (s->getId() == student->getId())
		{
			return; // już jest na liście
		}
	}
	studenci.push_back(student);
	// Dodaj kurs do studenta, jeśli nie ma
	auto kursyStudenta = student->getKursy();
	bool already = false;
	for (Kurs *k : *kursyStudenta)
	{
		if (k == this)
		{
			already = true;
			break;
		}
	}
	if (!already)
	{
		kursyStudenta->push_back(this);
	}
}

void Kurs::dodajWykladowce(Wykladowca *wykladowca)
{
	for (Wykladowca *w : wykladowcy)
	{
		if (w->getId() == wykladowca->getId())
		{
			return; // już jest na liście
		}
	}
	wykladowcy.push_back(wykladowca);
}

bool Kurs::usunSkrzynke(int id)
{
	for (Skrzynka *skrzynka : skrzynkiPlikow)
	{
		if (skrzynka->getId() == id)
		{
			skrzynkiPlikow.remove(skrzynka);
			return true;
		}
	}
	return false;
}

bool Kurs::usunOcene(Ocena *ocena)
{
	for (Ocena *o : oceny)
	{
		if (o->getWartosc() == ocena->getWartosc() && o->getAdresat() == ocena->getAdresat())
		{
			oceny.remove(ocena);
			return true;
		}
	}
	return false;
}

bool Kurs::usunUczestnika(int id)
{
	for (Student *s : studenci)
	{
		if (s->getId() == id)
		{
			studenci.remove(s);
			return true;
		}
	}
	for (Wykladowca *w : wykladowcy)
	{
		if (w->getId() == id)
		{
			wykladowcy.remove(w);
			return true;
		}
	}
	return false;
}

void Kurs::dodajPlikDoSkrzynki(int idSkrzynki, Plik *plik)
{
	for (Skrzynka *skrzynka : skrzynkiPlikow)
	{
		if (skrzynka->getId() == idSkrzynki)
		{
			skrzynka->setPlik(plik);
		}
	}
}

Kurs::Kurs(string nazwa, Wykladowca *prowadzacy) : nazwa(nazwa)
{
	wykladowcy.push_back(prowadzacy);
}
