//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kurs.h
//  @ Date : 19.05.2025
//  @ Author :
//
//

#if !defined(_KURS_H)
#define _KURS_H

#pragma once
#include <list>
#include <string>
#include <iostream>
using namespace std;

class User;
class Student;
class Wykladowca;
class Skrzynka;
class Ocena;
class Plik;

class Kurs
{
public:
	string getNazwa();
	list<Student *> getStudenci();
	list<Wykladowca *> getWykladowcy();
	list<Skrzynka *> getSkrzynki();
	list<Ocena *> getOceny();
	void dodajSkrzynke(Skrzynka *skrzynka);
	void dodajOcene(Ocena *ocena);
	void dodajStudenta(Student *student);
	void dodajWykladowce(Wykladowca *wykladowca);
	bool usunSkrzynke(int id);
	bool usunOcene(Ocena *ocena);
	bool usunUczestnika(int id);
	void dodajPlikDoSkrzynki(int idSkrzynki, Plik *plik);
	Kurs(string nazwa, Wykladowca *prowadzacy);

private:
	string nazwa;
	list<Ocena *> oceny;
	list<Student *> studenci;
	list<Wykladowca *> wykladowcy;
	list<Skrzynka *> skrzynkiPlikow;
};

#endif //_KURS_H
