//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ocena.cpp
//  @ Date : 19.05.2025
//  @ Author : 
//
//


#include "Ocena.h"
#include "Student.h"

int Ocena::getWartosc() {

}

Student* Ocena::getAdresat() {

}

Ocena::Ocena(int wartosc, Student* adresat) {

}

