//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ocena.h
//  @ Date : 19.05.2025
//  @ Author : overstimulation
//
//

#if !defined(_OCENA_H)
#define _OCENA_H

#pragma once
#include <list>
#include <string>
#include <iostream>
using namespace std;

class Student;

class Ocena
{
public:
	int getWartosc();
	Student *getAdresat();
	string getPrzedmiot();
	Ocena(int wartosc, string przedmiot, Student *adresat);

private:
	int wartosc;
	string przedmiot;
	Student *adresatOceny;
};

#endif //_OCENA_H
