//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ocena.cpp
//  @ Date : 19.05.2025
//  @ Author : overstimulation
//
//

#include "Ocena.h"
#include "Student.h"

int Ocena::getWartosc()
{
    return wartosc;
}

Student *Ocena::getAdresat()
{
    return adresatOceny;
}

string Ocena::getPrzedmiot()
{
    return przedmiot;
}

Ocena::Ocena(int wartosc, string przedmiot, Student *adresat) : wartosc(wartosc), przedmiot(przedmiot), adresatOceny(adresat) {}
