//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Plik.cpp
//  @ Date : 19.05.2025
//  @ Author : 
//
//


#include "Plik.h"

string Plik::getNazwa() {

}

int Plik::getRozmiar() {

}

string Plik::getDataDodania() {

}

string Plik::getTresc() {

}

Plik::Plik(string nazwa, int rozmiar, string tresc) {

}

