//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Plik.h
//  @ Date : 19.05.2025
//  @ Author : 
//
//


#if !defined(_PLIK_H)
#define _PLIK_H

#pragma once
#include <list>
#include <string>
#include <iostream>
using namespace std;

class Plik {
public:
	string getNazwa();
	int getRozmiar();
	string getDataDodania();
	string getTresc();
	Plik(string nazwa, int rozmiar, string tresc);
private:
	string nazwa;
	int rozmiar;
	string dataDodania;
	string tresc;
};

#endif  //_PLIK_H
