//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Poczta.h
//  @ Date : 19.05.2025
//  @ Author : overstimulation
//
//

#if !defined(_POCZTA_H)
#define _POCZTA_H

#pragma once
#include <list>
#include <string>
#include <iostream>
using namespace std;

class User;
class Wiadomosc;

class Poczta
{
public:
	list<Wiadomosc *> getWiadomosci(User *odbiorca);
	void wyslijWiadomosc(Wiadomosc *wiadomosc);
	Poczta();

private:
	list<Wiadomosc *> wiadomosci;
};

#endif //_POCZTA_H
