//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Poczta.cpp
//  @ Date : 19.05.2025
//  @ Author : 
//
//


#include "Poczta.h"
#include "User.h"
#include "Wiadomosc.h"

list<Wiadomosc*> Poczta::getWiadomosci(User* odbiorca) {

}

void Poczta::wyslijWiadomosc(Wiadomosc* wiadomosc) {

}

Poczta::Poczta() {

}

