//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Skrzynka.cpp
//  @ Date : 19.05.2025
//  @ Author : overstimulation
//
//

#include "Skrzynka.h"
#include "Plik.h"

int Skrzynka::nextId = 1;

int Skrzynka::getId()
{
    return id;
}

string Skrzynka::getNazwa()
{
    return nazwa;
}

Plik *Skrzynka::getPlik()
{
    return plik;
}

void Skrzynka::setPlik(Plik *plik)
{
    this->plik = plik;
}

Skrzynka::Skrzynka(string nazwa) : nazwa(nazwa)
{
    id = nextId++;
    plik = nullptr;
}
