//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Skrzynka.h
//  @ Date : 19.05.2025
//  @ Author : 
//
//


#if !defined(_SKRZYNKA_H)
#define _SKRZYNKA_H

#pragma once
#include <list>
#include <string>
#include <iostream>
using namespace std;

class Plik;

class Skrzynka {
public:
	int getId();
	string getNazwa();
	Plik* getPlik();
	void setPlik(Plik* plik);
	Skrzynka(string nazwa);
private:
	int id;
	string nazwa;
	Plik* plik;
};

#endif  //_SKRZYNKA_H
