//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Skrzynka.cpp
//  @ Date : 19.05.2025
//  @ Author : 
//
//


#include "Skrzynka.h"
#include "Plik.h"

int Skrzynka::getId() {

}

int Skrzynka::getNazwa() {

}

Plik* Skrzynka::getPlik() {

}

void Skrzynka::setPlik(Plik* plik) {

}

Skrzynka::Skrzynka(string nazwa) {

}

