//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Skrzynka.cpp
//  @ Date : 19.05.2025
//  @ Author :
//
//

#include "Skrzynka.h"
#include "Plik.h"

int Skrzynka::getId()
{
    return id;
}

string Skrzynka::getNazwa()
{
    return nazwa;
}

Plik *Skrzynka::getPlik()
{
    return plik;
}

void Skrzynka::setPlik(Plik *plik)
{
    // TODO: implementacja
}

Skrzynka::Skrzynka(string nazwa) : nazwa(nazwa) {}
