//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.cpp
//  @ Date : 19.05.2025
//  @ Author : overstimulation
//
//

#include "Student.h"

int Student::getNrIndeksu()
{
    return nrIndeksu;
}

int Student::getRokStudiow()
{
    return rokStudiow;
}

int Student::getStopienStudiow()
{
    return stopienStudiow;
}

Student::Student(string imie, string nazwisko, Wydzial *wydzial, int indeks, int rok, int stopien)
    : User(imie, nazwisko, wydzial, "student"), nrIndeksu(indeks), rokStudiow(rok), stopienStudiow(stopien) {}
