//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.h
//  @ Date : 19.05.2025
//  @ Author : overstimulation
//
//


#if !defined(_STUDENT_H)
#define _STUDENT_H

#pragma once
#include <list>
#include <string>
#include <iostream>
using namespace std;
#include "User.h"

class Student : public User {
public:
	int getNrIndeksu();
	int getRokStudiow();
	int getStopienStudiow();
	Student(string imie, string nazwisko, Wydzial* wydzial, int indeks, int rok, int stopien);
private:
	int nrIndeksu;
	int rokStudiow;
	int stopienStudiow;
};

#endif  //_STUDENT_H
