//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.cpp
//  @ Date : 19.05.2025
//  @ Author : 
//
//


#include "Student.h"

int Student::getNrIndeksu() {

}

int Student::getRokStudiow() {

}

int Student::getStopienStudiow() {

}

Student::Student(string imie, string nazwisko, Wydzial* wydzial, int indeks, int rok, int stopien) : User(imie, nazwisko, wydzial) {

}

