//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uczelnia.cpp
//  @ Date : 19.05.2025
//  @ Author : 
//
//


#include "Uczelnia.h"
#include "Wydzial.h"
#include "Student.h"
#include "Wykladowca.h"

string Uczelnia::getNazwa() {

}

string Uczelnia::getAdres() {

}

list<Wydzial*> Uczelnia::getWydzialy() {

}

list<Student*> Uczelnia::getStudenci() {

}

list<Wykladowca*> Uczelnia::getWykladowcy() {

}

void Uczelnia::dodajWydzial(Wydzial* wydzial) {

}

void Uczelnia::dodajStudenta(Student* student) {

}

void Uczelnia::dodajWykladowce(Wykladowca* wykladowca) {

}

void Uczelnia::usunWydzial(Wydzial* wydzial) {

}

void Uczelnia::usunStudenta(Student* student) {

}

void Uczelnia::usunWykladowce(Wykladowca* wykladowca) {

}

Uczelnia::Uczelnia(string nazwa, string adres) {

}

