//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.cpp
//  @ Date : 19.05.2025
//  @ Author : 
//
//


#include "User.h"
#include "Wydzial.h"
#include "Kurs.h"
#include "Wiadomosc.h"

int User::getId() {

}

string User::getImie() {

}

string User::getNazwisko() {

}

string User::getEmail() {

}

string User::getLogin() {

}

string User::getHaslo() {

}

bool User::getZalogowany() {

}

Wydzial* User::getWydzial() {

}

list<Kurs*>* User::getKursy() {

}

list<Wiadomosc*> User::sprawdzWiadomosci() {

}

void User::wyslijWiadomosc() {

}

void User::zarejestruj() {

}

bool User::weryfikuj() {

}

bool User::zaloguj() {

}

void User::wyloguj() {

}

User::User(string imie, string nazwisko, Wydzial* wydzial) {

}

