//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.h
//  @ Date : 19.05.2025
//  @ Author :
//
//


#if !defined(_USER_H)
#define _USER_H

#pragma once
#include <list>
#include <string>
#include <iostream>
using namespace std;

class Wydzial;
class Kurs;
class Wiadomosc;
class Poczta;
class Uczelnia;
class Student;
class Wykladowca;

class User {
public:
	int getId();
	string getImie();
	string getNazwisko();
	string getEmail();
	string getLogin();
	string getHaslo();
    bool getZalogowany();
    Wydzial* getWydzial();
	list<Kurs*>* getKursy();
    void setLogin(string login);
    void setHaslo(string haslo);
	list<Wiadomosc*> sprawdzWiadomosci(Poczta* poczta);
	void wyslijWiadomosc(Poczta* poczta, Wiadomosc* wiadomosc);
	static User* zarejestruj(Uczelnia* uczelnia);
	bool weryfikuj(const string& login, const string& haslo);
	static User* zaloguj(const string& login, const string& haslo, list<User*>& uzytkownicy,Uczelnia* uczelnia);
	void wyloguj();
	User(string imie, string nazwisko, Wydzial* wydzial);
private:
	int id;
	string imie;
	string nazwisko;
	string email;
	string login;
	string haslo;
	bool zalogowany;
	Wydzial* wydzial;
	list<Kurs*>* kursy;
};

#endif  //_USER_H
