//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.h
//  @ Date : 19.05.2025
//  @ Author :
//
//


#if !defined(_USER_H)
#define _USER_H

#pragma once
#include <list>
#include <string>
#include <iostream>
using namespace std;

class Wydzial;
class Kurs;
class Wiadomosc;
class Poczta;


class User {
public:
	int getId();
	string getImie();
	string getNazwisko();
	string getEmail();
	string getLogin();
	string getHaslo();
	bool getZalogowany();
	Wydzial* getWydzial();
	list<Kurs*>* getKursy();
	list<Wiadomosc*> sprawdzWiadomosci(Poczta* poczta);
	void wyslijWiadomosc(Poczta* poczta, Wiadomosc* wiadomosc);
	void zarejestruj();
	bool weryfikuj();
	bool zaloguj();
	void wyloguj();
	User(string imie, string nazwisko, Wydzial* wydzial);
private:
	int id;
	string imie;
	string nazwisko;
	string email;
	string login;
	string haslo;
	bool zalogowany;
	Wydzial* wydzial;
	list<Kurs*>* kursy;
};

#endif  //_USER_H
