//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wiadomosc.cpp
//  @ Date : 19.05.2025
//  @ Author : 
//
//


#include "Wiadomosc.h"
#include "User.h"

string Wiadomosc::getTemat() {

}

string Wiadomosc::getTresc() {

}

string Wiadomosc::getData() {

}

User* Wiadomosc::getOdbiorca() {

}

User* Wiadomosc::getNadawca() {

}

Wiadomosc::Wiadomosc(string temat, string tresc, string data, User* odbiorca, User* nadawca) {

}

