//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wiadomosc.cpp
//  @ Date : 19.05.2025
//  @ Author : overstimulation
//
//

#include "Wiadomosc.h"
#include "User.h"

string Wiadomosc::getTemat()
{
    return temat;
}

string Wiadomosc::getTresc()
{
    return tresc;
}

string Wiadomosc::getData()
{
    return data;
}

User *Wiadomosc::getOdbiorca()
{
    return odbiorca;
}

User *Wiadomosc::getNadawca()
{
    return nadawca;
}

Wiadomosc::Wiadomosc(string temat, string tresc, string data, User *odbiorca, User *nadawca)
    : temat(temat), tresc(tresc), data(data), odbiorca(odbiorca), nadawca(nadawca) {}
