//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wiadomosc.h
//  @ Date : 19.05.2025
//  @ Author : overstimulation
//
//

#if !defined(_WIADOMOSC_H)
#define _WIADOMOSC_H

#pragma once
#include <list>
#include <string>
#include <iostream>
using namespace std;

class User;

class Wiadomosc
{
public:
	string getTemat();
	string getTresc();
	string getData();
	User *getOdbiorca();
	User *getNadawca();
	Wiadomosc(string temat, string tresc, string data, User *odbiorca, User *nadawca);

private:
	string temat;
	string tresc;
	string data;
	User *odbiorca;
	User *nadawca;
};

#endif //_WIADOMOSC_H
