//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wydzial.cpp
//  @ Date : 19.05.2025
//  @ Author :
//
//


#include "Wydzial.h"
#include "Kurs.h"
#include "Student.h"
#include "Wykladowca.h"
#include "Uczelnia.h"

string Wydzial::getNazwa() {
    return nazwa;
}

list<Kurs*> Wydzial::getKursy() {
    return kursy;
}

Uczelnia* Wydzial::getUczelnia() {
    return uczelnia;
}

list<Student*> Wydzial::getStudenci() {
    return studenci;
}

list<Wykladowca*> Wydzial::getWykladowcy() {
    return wykladowcy;
}

void Wydzial::dodajKurs(Kurs* kurs) {
    kursy.push_back(kurs);
}

void Wydzial::dodajStudenta(Student* student) {
    studenci.push_back(student);
}

void Wydzial::dodajWykladowce(Wykladowca* wykladowca) {
    wykladowcy.push_back(wykladowca);
}

bool Wydzial::usunKurs(Kurs* kurs) {
	for(Kurs *k : kursy) {
		if(k->getNazwa() == kurs->getNazwa()) {
			kursy.remove(kurs);
			return true;
		}
	}
	return false;
}

bool Wydzial::usunStudenta(Student* student) {
	for(Student *s : studenci) {
		if(s->getId() == student->getId()) {
			studenci.remove(student);
			return true;
		}
	}
	return false;
}

bool Wydzial::usunWykladowce(Wykladowca* wykladowca) {
	for(Wykladowca *w : wykladowcy) {
		if(w->getId() == wykladowca->getId()) {
			wykladowcy.remove(wykladowca);
			return true;
		}
	}
	return false;
}

Wydzial::Wydzial(string nazwa, Uczelnia* uczelnia)
    : nazwa(nazwa), uczelnia(uczelnia) {
		uczelnia->dodajWydzial(this);
	}

