//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wydzial.h
//  @ Date : 19.05.2025
//  @ Author :
//
//


#if !defined(_WYDZIAL_H)
#define _WYDZIAL_H

#pragma once
#include <list>
#include <string>
#include <iostream>
using namespace std;

class Kurs;
class Student;
class Wykladowca;
class Uczelnia;

class Wydzial {
public:
	string getNazwa();
	list<Kurs*> getKursy();
	Uczelnia* getUczelnia();
	list<Student*> getStudenci();
	list<Wykladowca*> getWykladowcy();
	void dodajKurs(Kurs* kurs);
	void dodajStudenta(Student* student);
	void dodajWykladowce(Wykladowca* wykladowca);
	bool usunKurs(Kurs* kurs);
	bool usunStudenta(Student* student);
	bool usunWykladowce(Wykladowca* wykladowca);
	Wydzial(string nazwa, Uczelnia* uczelnia);
private:
	string nazwa;
	list<Kurs*> kursy;
	list<Student*> studenci;
	list<Wykladowca*> wykladowcy;
	Uczelnia* uczelnia;
};

#endif  //_WYDZIAL_H
