//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wydzial.cpp
//  @ Date : 19.05.2025
//  @ Author : 
//
//


#include "Wydzial.h"
#include "Kurs.h"
#include "Student.h"
#include "Wykladowca.h"
#include "Uczelnia.h"

string Wydzial::getNazwa() {

}

list<Kurs> Wydzial::getKursy() {

}

Uczelnia* Wydzial::getUczelnia() {

}

list<Student*> Wydzial::getStudenci() {

}

list<Wykladowca*> Wydzial::getWykladowcy() {

}

void Wydzial::dodajKurs(Kurs* kurs) {

}

void Wydzial::dodajStudenta(Student* student) {

}

void Wydzial::dodajWykladowce(Wykladowca* wykladowca) {

}

bool Wydzial::usunKurs(Kurs* kurs) {

}

bool Wydzial::usunStudenta(Student* student) {

}

bool Wydzial::usunWykladowce(Wykladowca* wykladowca) {

}

Wydzial::Wydzial(string nazwa, Uczelnia* uczelnia) {

}

