//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wykladowca.cpp
//  @ Date : 19.05.2025
//  @ Author : overstimulation
//
//

#include "Wykladowca.h"
#include "Kurs.h"

string Wykladowca::getTytulNaukowy()
{
    return tytulNaukowy;
}

string Wykladowca::getSpecjalizacja()
{
    return specjalizacja;
}

Wydzial *Wykladowca::getWydzial()
{
    return User::getWydzial();
}

void Wykladowca::stworzKurs()
{
    Wydzial *mojWydzial = this->getWydzial();
    cout << "--- Panel tworzenia kursu ---" << endl;
    string nazwa;
    bool kursIstnieje = false;
    do
    {
        cout << "Podaj nazwe kursu: ";
        getline(cin, nazwa);
        kursIstnieje = false;
        for (Kurs* kurs : mojWydzial->getKursy())
        {
            if (kurs->getNazwa() == nazwa)
            {
                kursIstnieje = true;
                cout << "Kurs o nazwie '" << nazwa << "' juz istnieje. Podaj inna nazwe.\n";
                break;
            }
        }
    } while (kursIstnieje);
    Kurs *nowyKurs = new Kurs(nazwa, this);
    mojWydzial->dodajKurs(nowyKurs);
    cout << "Kurs '" << nazwa << "' zostal dodany do bazy aktywnych kursow." << endl;
}

Wykladowca::Wykladowca(string imie, string nazwisko, Wydzial *wydzial, string tytul, string specjalizacja)
    : User(imie, nazwisko, wydzial, "wykladowca"), tytulNaukowy(tytul), specjalizacja(specjalizacja) {}
